name: BasicsSpawn
version: '${project.version}'
main: com.soyaldo.basicsspawn.BasicsSpawn
api-version: 1.13
authors: [ SoyAldo ]
description: Description
website: https://www.spigotmc.org/resources/107590/
commands:
  basicsspawnadmin:
    aliases:
      - "bsa"
  basicsspawn:
    aliases:
      - "bspawn"
      - "spawn"
permissions:
  basicsspawn.admin:
    description: "Access to all commands."
    children:
      basicsspawn.spawn: true
      basicsspawn.spawn.other: true
  basicsspawn.spawn:
    description: "Access to /spawn command."
  basicsspawn.spawn.other:
    description: "Access to /spawn [player] command."
